---
version: 3
project:
  id: gooddata-ui-sdk

telemetry:
  scope: 'off'

targets:
  only:
    - type: pnpm
      path: common/config/rush

  #only:
  #  - type: bundler
  #    path: libs/sdk-model
  #only:
  #  - type: pnpm
  #    path: common/config/rush
  #exclude:
    #- type: bundler
    #  path: tools/applink
