name: Get current version of the sdk
description: This action assumes nodejs installed and repository checkouted

outputs:
  version:
    description: current version
    value: ${{ steps.version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - id: version
      run: echo "version=$(node -p "require('./libs/sdk-ui/package.json').version")" >> $GITHUB_OUTPUT
