# (C) 2024 GoodData Corporation

# Deploy of ui sdk examples
name: Doc ~ Examples deploy
on:
  workflow_dispatch:

jobs:
  release-ui-sdk-examples-deploy:
    secrets: inherit
    uses: ./.github/workflows/rw-doc-storybook-deploy.yml
    with:
      source-branch: "master"
