name: Git ~ Merge Test
on:
    workflow_dispatch:
jobs:
    auto-merge:
        uses: ./.github/workflows/rw-git-merge-test.yml
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        secrets: inherit
        with:
            branch_name: "release"
    
    slack-notification:
        runs-on: [ubuntu-latest]
        needs: [auto-merge]
        steps:
        - name: Notify to slack
          uses: slackapi/slack-github-action@v1.25.0
          with:
            channel-id: "#sdk-wf-test"
            slack-message: "The release backmerge is prepared and ready to be merged into the master upon approval of the open pull request. ${{env.PR_URL }}"
          env:            
            PR_URL: ${{ needs.auto-merge.outputs.pr-url }}