name: Git ~ Merge Test
on:
    workflow_dispatch:
jobs:
    auto-merge:
        uses: ./.github/workflows/rw-git-merge-test.yml
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        secrets: inherit
        with:
            branch_name: "release"
    
    slack-notification:
        runs-on: [ubuntu-latest]
        needs: [auto-merge]
        steps:
        - name: Notify to slack
          uses: slackapi/slack-github-action@v1.25.0
          with:
            channel-id: "#sdk-wf-test"
            slack-message: "The backmerge from the release is ready and waiting to be merged into the master branch once the open pull request is reviewed and merged. ${{env.PULL_REQUEST }}"
          env:            
            PULL_REQUEST: ${{ needs.auto-merge.outputs.pull_request_url }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}