name: Git ~ Merge Test
on:
    workflow_dispatch:
jobs:
    update-hugo-version:
        uses: ./.github/workflows/rw-git-merge-test.yml
        permissions:
            contents: write
            id-token: write
        secrets: inherit
        with:
            branch_name: "release"            