# (C) 2024 GoodData Corporation

name: Pull request ~ Prerelease
on:
  push:    
    branches:
      - master
      - release

jobs:
  get-label-and-author-from-pr:
    runs-on: [ubuntu-latest]
    outputs:
      should-prerelease: ${{ steps.pr_info.outputs.result.shouldPrerelease }}
      author: ${{ steps.pr_info.outputs.result.author }}
      branch-name: ${{ steps.extract-branch.outputs.branch }}
    steps:
      - uses: actions/github-script@v7
        id: pr_info
        with:
          script: |
            const pullRequests = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const pr = pullRequests?.data[0];
            const shouldPrerelease = pr?.labels?.some((it)=>it.name==='publish pre-release');
            const author = pr?.user?.login;
            return { shouldPrerelease, author };
          result-encoding: string
      - name: Extract branch name
        env:
          CURRENT_REF: ${{ github.event.ref }}
        id: extract-branch
        shell: bash
        run: echo "branch=${CURRENT_REF#refs/heads/}" >> $GITHUB_OUTPUT
  
  echo-results:
    runs-on: [ubuntu-latest]
    needs: [get-label-and-author-from-pr]
    steps:
      - name: Echo results
        run: |
          echo "should-prerelease: ${{ needs.get-label-and-author-from-pr.outputs.should-prerelease }}"
          echo "author: ${{ needs.get-label-and-author-from-pr.outputs.author }}"
          echo "branch-name: ${{ needs.get-label-and-author-from-pr.outputs.brach-name }}"

  publish-pre-release:
    needs: [get-label-and-author-from-pr]
    name: Publish pre-release
    if: ${{ needs.get-label-and-author-from-pr.outputs.should-prerelease == 'true' }}        
    uses: ./.github/workflows/rw-publish-prerelease.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:      
      source-branch:  ${{ needs.get-label-and-author-from-pr.outputs.brach-name }}
