# (C) 2024 GoodData Corporation

#zmena 2

name: Pull request ~ Prerelease
on:
  push:    
    branches:
      - master
      - release

jobs:
  get-label-from-pr:
    runs-on: [ubuntu-latest]
    outputs:
        should-prerelease: ${{ steps.needs-prerelease.outputs.result.shouldprerelease }}
        brach-name: ${{ steps.extract-branch.outputs.branch }}
    steps:
      - uses: actions/github-script@v7
        id: needs-prerelease
        with:
          script: |          
              const pullRequests = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              const res = pullRequests?.data[0]?.labels?.some((it)=>it.name==='publish pre-release');
              const result = { shouldprerelease: res };
          result-encoding: string
      - name: Extract branch name
        env:
          CURRENT_REF: ${{ github.event.ref }}
        id: extract-branch
        shell: bash
        run: echo "branch=${CURRENT_REF#refs/heads/}" >> $GITHUB_OUTPUT
  
  echo-results:
    runs-on: [ubuntu-latest]
    needs: [get-label-from-pr]
    steps:
      - name: Echo results
        run: |
          echo "should-prerelease: ${{ needs.get-label-from-pr.outputs.should-prerelease }}"
          echo "author: ${{ needs.get-label-from-pr.outputs.author }}"
          echo "branch-name: ${{ needs.get-label-from-pr.outputs.brach-name }}"