# (C) 2024 GoodData Corporation

name: Release ~ Release patch version
on:
  workflow_dispatch:
      inputs:
        version:
            required: true
            description: "Specify the minor version to patch (example: 9.5.0)"
            type: string

jobs:
    check-version:
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.check-version.outputs.branch }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              # TODO: can we use our existing action?
            - name: Check if version is
              id: check-version
              run: |
                  base="rel/${VERSION%.*}"
                  # TODO: brackets for if?
                  if git ls-remote --heads origin ${base} | grep ${base}; then
                    echo "Branch ${base} exists for version ${VERSION}"
                    echo "branch=${base} >> $GITHUB_OUTPUT"
                  else
                    echo "Branch ${base} does not exist for release ${VERSION} on remote, aborting release"
                    exit 1
                  fi
              env:
                  VERSION: ${{ inputs.version }}

    gate-approval:
        needs: check-version
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - run: echo "Initiating approval"


    publish-release-npm:
      needs: [gate-approval, check-version]
      uses: ./.github/workflows/rw-perform-release-major-minor.yml
      permissions:
        pull-requests: write
        contents: write
      secrets: inherit
      with:
        bump: "patch"
        source-branch: ${{needs.check-version.outputs.branch}}
