# (C) 2024 GoodData Corporation

# This workflow is triggered by a workflow call. It will bump the version of the repository and push the changes to the source branch.
# It will also return the version which was created.
# if the 'skip-bump' input is set to true, it will just return the current version without bumping it.

name: rw ~ Rush ~ Bump version
on:
    workflow_call:
        inputs:
            source-branch:
                required: true
                description: "The name of the source branch"
                type: string
            prerelease-id:
                required: true                
                description: "The prerelease ID (alpha, beta, etc.)"
                type: string
        outputs:
            version:
                description: "Version which was created"
                value: ${{ jobs.get-version.outputs.version }}

jobs:
    bump-version-and-commit:        
        runs-on: [ubuntu-latest]
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18.17.0
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.source-branch }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Add repository to git safe directories to avoid dubious ownership issue
              run: git config --global --add safe.directory $GITHUB_WORKSPACE

            - name: Install rush
              run: npm install -g @microsoft/rush

            - name: Config user
              run: |
                  git config --global user.email "git-action@gooddata.com"
                  git config --global user.name "git-action"
            - name: Get current version
              uses: gooddata/gooddata-ui-sdk/.github/actions/get-version-action@master
              id: current_version

            - name: Prepare next major version
              env:
                  VERSION: ${{ steps.current_version.outputs.version }}
                  PRERELEASE_ID: ${{ inputs.prerelease-id }}
              run: |
                echo "Bumping version to next major from ${VERSION}"

                # Extract the major version
                major_version=$(echo $current_version | cut -d '.' -f 1)

                echo "current major version: ${major_version}"

                # Increment the major version
                next_major_version=$((major_version + 1))

                # Construct the next version string
                next_version="${next_major_version}.0.0-${PRERELEASE_ID}.0"

                echo "Next version: $next_version"

            - name: Get version
              uses: gooddata/gooddata-ui-sdk/.github/actions/get-version-action@master
              id: version

            # - name: Git commit and push
            #   run: |
            #     # add changelogs
            #     git ls-files | grep '\.json' | xargs git add

            #     git commit -a -m "Bump versions to $VERSION"
            #     git push origin ${{ inputs.source-branch }}
            #   env:
            #     VERSION: ${{ steps.version.outputs.version }}
