# (C) 2024 GoodData Corporation

name: rw ~ Release ~ Publish release
on:
  workflow_call:
    inputs:
      bump:
        required: true
        description: "The type of version bump (major, minor, patch)"
        type: string
    outputs:
      version:
        description: "Version which was created"
        value: ${{ jobs.bump-version.outputs.version }}

# limit concurrency to one run per branch at a time
# so that we can run this from master and a release branch at the same time
# When a concurrent job or workflow is queued,
# if another job or workflow using the same concurrency group in the repository is in progress,
# the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled.
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  bump-version:
    uses: ./.github/workflows/rw-bump-version.yml    
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      source-branch: "release"
      bump: ${{ inputs.bump }}

  publish-release:
    needs: [bump-version]
    uses: ./.github/workflows/rw-publish-version.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      source-branch: "release"
      release-tag: "latest"
  
  check-npm-package:
    runs-on: [ubuntu-latest]
    needs: [bump-version,publish-release]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Check NPM package
        uses: ./.github/actions/check-npm-version
        with:
          package: "@gooddata/sdk-ui"
          version: ${{ needs.bump-version.outputs.version }}          
        
  slack-notification:
    runs-on: [ubuntu-latest]
    needs: [bump-version, check-npm-package]
    steps:
      - name: Notify to slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "#sdk-wf-test"
          slack-message: "The latest *${{ env.BUMP }}* version, *gooddata-ui-sdk@${{ env.RELEASE_VERSION }}*, has been successfully published on NPM by the user *${{env.GITHUB_USER}}*. :tada:"
        env:
          RELEASE_VERSION: ${{ needs.bump-version.outputs.version }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          BUMP: ${{ inputs.bump }}
          GITHUB_USER: ${{ github.actor }}
# add waring when check-npm-package fails