# (C) 2024 GoodData Corporation
#test 2

name: rw ~ Release ~ Publish prerelease
on:
  workflow_call:
    inputs:
      source-branch:
        required: true
        description: "The name of the source branch"
        type: string
      skip-bump:
        required: false
        default: false
        description: "Skip bumping the version"
        type: boolean
      author-name:
        required: false
        description: "The name of the author"
        type: string

# limit concurrency to one run per branch at a time
# so that we can run this from master and a release branch at the same time
# When a concurrent job or workflow is queued,
# if another job or workflow using the same concurrency group in the repository is in progress,
# the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled.
concurrency:
  group: prerelease-${{ inputs.source-branch }}
  cancel-in-progress: false

jobs:
  setup-params:
    runs-on: [ubuntu-latest]
    outputs:
      prerelease-id: ${{ steps.validate-params.outputs.prerelease-id }}

    steps:
      - name: validate params
        id: validate-params
        run: |
          if [ "${{ inputs.source-branch }}" = "master" ]; then
            echo "prerelease-id=alpha" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.source-branch }}" = "release" ]; then
            echo "prerelease-id=beta" >> $GITHUB_OUTPUT
          else
            echo "Invalid branch provided. Please provide either 'master' or 'release'."
            exit 1
          fi

  bump-version:
    needs: [setup-params]
    uses: ./.github/workflows/rw-bump-version.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      source-branch: ${{ inputs.source-branch }}
      bump: "prerelease"
      prerelease-id: ${{ needs.setup-params.outputs.prerelease-id }}
      skip-bump: ${{ inputs.skip-bump }}

  publish-prerelease:
    needs: [bump-version]
    uses: ./.github/workflows/rw-publish-version.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      source-branch: ${{ inputs.source-branch }}
      release-tag: "prerelease"

  slack-notification:
    runs-on: [ubuntu-latest]
    needs: [bump-version, publish-prerelease]
    steps:
      - name: Notify to slack with author name
        if: ${{ inputs.author-name != '' }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "#javascript-notifications"
          slack-message: "The latest *prerelase* version, *gooddata-ui-sdk@${{ env.RELEASE_VERSION }}*, has been successfully published on NPM by the user *${{env.GITHUB_USER}}*. :tada:"
        env:
          RELEASE_VERSION: ${{ needs.bump-version.outputs.version }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_USER: ${{ inputs.author-name }}
      - name: Notify to slack with without author name
        if: ${{ inputs.author-name == '' }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "#javascript-notifications"
          slack-message: "The latest *prerelase* version, *gooddata-ui-sdk@${{ env.RELEASE_VERSION }}*, has been successfully published on NPM. :tada:"
        env:
          RELEASE_VERSION: ${{ needs.bump-version.outputs.version }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_USER: ${{ inputs.author-name }}
