# (C) 2024 GoodData Corporation

name: rw ~ Rush ~ Publish version
on:
    workflow_call:
        inputs:
            source-branch:
                required: true
                description: "The name of the source branch"
                type: string
            release-tag:
                required: true
                description: "The release NPM tag e.g. prerelease, latest, hotfix ..."
                type: string

jobs:
    publish-version:
        runs-on: [ubuntu-latest]
        permissions:
            contents: read
        steps:
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18.17.0
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.source-branch }}
                  #            - name: Add repository to git safe directories to avoid dubious ownership issue
                  #              run: git config --global --add safe.directory $GITHUB_WORKSPACE
                  #            - name: Install rush
                  #              run: |
                  #                  npm install -g @microsoft/rush
                  #            - name: Rush install
                  #              run: |
                  #                  rush install
                  #            - name: Rush build
                  #              run: |
                  #                  rush build
                  #            - name: Rush publish dry run
                  #              run: |
                  #                  rush publish --include-all --version-policy sdk --set-access-level public
                  #            - name: Rush publish
                  #              env:
                  #                  TAG: ${{ inputs.release-tag }}
                  #                  NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
                  #              run: |
                  #                  rush publish --publish --include-all --version-policy sdk --tag $TAG --set-access-level public
