name: rw ~ rush ~ e2e tests
on:
  workflow_call:
    inputs:
      filter:
          required: false
          description: "List of spec files to filter"
          type: string
      source-ref:
          required: false
          description: "source ref of the current code"
          type: string

jobs:
  warm-up-cache:
    runs-on:
     ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-ref }}
          fetch-depth: 2
