name: Manual trigger
description: 'test commit to protected master branch'
on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_GITHUB_YENKINS }}
        ref: 'master'

    - name: Make empty commit
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git commit --allow-empty -m 'Empty commit'
        git push